import { Entities } from './types/core.js'
import type { DBTableInfoMap } from './types/core.js'

export const dbTableInfo: DBTableInfoMap = {
  countries: {
    table: 'countries',
    columns: ['country_id', 'country']
  },
  stadiums: {
    table: 'stadiums',
    columns: [
      'stadium_id',
      'stadium',
      'city',
      'capacity',
      'inaguration',
      'surface'
    ]
  },
  teams: {
    table: 'teams',
    columns: ['team_id', 'name', 'country_id', 'stadium_id']
  },
  players: {
    table: 'players',
    columns: [
      'player_id',
      'player_name',
      'shirt_number',
      'height',
      'market_value',
      'team_id',
      'country_id'
    ],
    dependenciesTables: [Entities.Positions, Entities.PlayerPositions]
  },
  positions: {
    table: 'positions',
    columns: ['position_id', 'position']
  },
  playerPositions: {
    table: 'player_positions',
    columns: ['player_id', 'position_id']
  },
  matches: {
    table: 'matches',
    columns: [
      'match_id',
      'home_team_id',
      'visit_team_id',
      'attendance',
      'season',
      'competition',
      'match_week',
      'match_date',
      'stadium_id',
      'is_neutral',
      'was_game_finished',
      'was_game_cancelled',
      'first_half_started',
      'second_half_started',
      'first_half_ended',
      'second_half_ended',
      'highlights',
      'referee_id',
      'man_of_the_match'
    ],
    dependenciesTables: [
      Entities.MatchGoals,
      Entities.MatchAssits,
      Entities.MatchCards
    ]
  },
  matchGoals: {
    table: 'match_goals',
    columns: [
      'goal_id',
      'match_id',
      'player_id',
      'scored_for',
      'scored_to',
      'main_minute',
      'added_minute',
      'is_own_goal',
      'is_penalty'
    ]
  },
  matchAssists: {
    table: 'match_assists',
    columns: ['assists_id', 'player_id', 'goal_assisted', 'match_id']
  },
  matchCards: {
    table: 'match_cards',
    columns: [
      'mc_id',
      'match_id',
      'player_id',
      'card',
      'main_minute',
      'added_minute'
    ]
  },
  playerMatchStats: {
    table: 'player_matches_stats',
    columns: [
      'id',
      'player_id',
      'match_id',
      'accurate_crosses',
      'accurate_long_balls',
      'accurate_passes',
      'acted_as_sweeper',
      'aerial_duels_lost',
      'aerial_duels_won',
      'assists',
      'big_chances_missed',
      'blocked_shots',
      'blocks',
      'chances_created',
      'clearances',
      'clearance_off_the_line',
      'conceded_penalty',
      'corners',
      'crosses',
      'defensive_actions',
      'dispossessed',
      'diving_save',
      'dribbled_past',
      'duels_lost',
      'duels_won',
      'error_led_to_goal',
      'expected_assists_xa',
      'expected_goals_xg',
      'expected_goals_on_target_xgot',
      'fantasy_points',
      'fotmob_rating',
      'fouls_committed',
      'goals',
      'goals_conceded',
      'goals_prevented',
      'ground_duels_lost',
      'ground_duels_won',
      'headed_clearance',
      'high_claim',
      'hit_woodwork',
      'inaccurate_crosses',
      'inaccurate_long_balls',
      'inaccurate_passes',
      'interceptions',
      'last_man_tackle',
      'minutes_played',
      'missed_penalty',
      'offsides',
      'own_goal',
      'passes_into_final_third',
      'penalties_won',
      'punches',
      'recoveries',
      'saved_penalties',
      'saves',
      'saves_inside_box',
      'shotmap',
      'shots_off_target',
      'shots_on_target',
      'successful_dribbles',
      'tackles',
      'throws',
      'total_aerial_duels',
      'total_crosses',
      'total_dribbles',
      'total_ground_duels',
      'total_long_balls',
      'total_passes',
      'touches',
      'total_shots',
      'total_shots_on_target',
      'touches_in_opposition_box',
      'unsuccessful_dribbles',
      'was_fouled',
      'xg_plus_xa',
      'xg_non_penalty',
      'xgot_faced'
    ]
  },
  matchLineUps: {
    table: 'match_lineups',
    columns: ['lineup_id', 'match_id', 'team_id', 'lineup'],
    dependenciesTables: [Entities.MatchLineUpsPlayers]
  },
  matchLineUpsPlayers: {
    table: 'match_lineup_players',
    columns: ['ln_player_id', 'player_id', 'lineup_id', 'status']
  },
  firstHalfTeamStats: {
    table: 'first_half_match_team_stats',
    columns: [
      'id',
      'team_id',
      'match_id',
      'ball_possession',
      'expected_goals_xg',
      'total_shots',
      'shots_on_target',
      'big_chances',
      'big_chances_missed',
      'accurate_passes',
      'fouls_committed',
      'corners',
      'shots_off_target',
      'blocked_shots',
      'hit_woodwork',
      'shots_inside_box',
      'shots_outside_box',
      'xg_open_play',
      'xg_set_play',
      'xg_non_penalty',
      'xg_on_target_xgot',
      'passes',
      'own_half_passes',
      'opposition_half_passes',
      'accurate_long_balls',
      'accurate_crosses',
      'throws',
      'offsides',
      'tackles',
      'interceptions',
      'blocks',
      'clearances',
      'keeper_saves',
      'duels_won',
      'ground_duels_won',
      'aerial_duels_won',
      'successful_dribbles',
      'yellow_cards',
      'red_cards',
      'touches_in_opposition_box'
    ]
  },
  secondHalfTeamStats: {
    table: 'second_half_match_team_stats',
    columns: [
      'id',
      'team_id',
      'match_id',
      'ball_possession',
      'expected_goals_xg',
      'total_shots',
      'shots_on_target',
      'big_chances',
      'big_chances_missed',
      'accurate_passes',
      'fouls_committed',
      'corners',
      'shots_off_target',
      'blocked_shots',
      'hit_woodwork',
      'shots_inside_box',
      'shots_outside_box',
      'xg_open_play',
      'xg_set_play',
      'xg_non_penalty',
      'xg_on_target_xgot',
      'passes',
      'own_half_passes',
      'opposition_half_passes',
      'accurate_long_balls',
      'accurate_crosses',
      'throws',
      'offsides',
      'tackles',
      'interceptions',
      'blocks',
      'clearances',
      'keeper_saves',
      'duels_won',
      'ground_duels_won',
      'aerial_duels_won',
      'successful_dribbles',
      'yellow_cards',
      'red_cards',
      'touches_in_opposition_box'
    ]
  },
  fullMatchTeamStats: {
    table: 'full_match_team_stats',
    columns: [
      'id',
      'team_id',
      'match_id',
      'ball_possession',
      'expected_goals_xg',
      'total_shots',
      'shots_on_target',
      'big_chances',
      'big_chances_missed',
      'accurate_passes',
      'fouls_committed',
      'corners',
      'shots_off_target',
      'blocked_shots',
      'hit_woodwork',
      'shots_inside_box',
      'shots_outside_box',
      'xg_open_play',
      'xg_set_play',
      'xg_non_penalty',
      'xg_on_target_xgot',
      'passes',
      'own_half_passes',
      'opposition_half_passes',
      'accurate_long_balls',
      'accurate_crosses',
      'throws',
      'offsides',
      'tackles',
      'interceptions',
      'blocks',
      'clearances',
      'keeper_saves',
      'duels_won',
      'ground_duels_won',
      'aerial_duels_won',
      'successful_dribbles',
      'yellow_cards',
      'red_cards',
      'touches_in_opposition_box'
    ],
    dependenciesTables: [
      Entities.FirstHalfTeamStats,
      Entities.SecondHalfTeamStats
    ]
  }
}
